{{- if and .Values.deployments.agents (gt (.Values.query.replicaCount | int64) 0) -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "imply.query.fullname" . }}
  labels:
{{ include "imply.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "imply.query.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{ toYaml .Values.query.podDisruptionBudget | indent 2 }}
{{- end }}
