apiVersion: v2
name: jupyter
description: A Helm chart to deploy Jupyter
type: application
version: 0.2.10
appVersion: "584f43f06586"

home: https://github.com/luigidifraia/helm-charts

maintainers:
  - name: luigidifraia
