apiVersion: v1
appVersion: "2021.05-1"
description: Imply Manager
home: https://imply.io
icon: https://static.imply.io/imply-arrow.svg
keywords:
- druid
- imply
maintainers:
- email: contact@imply.io
  name: Imply
name: imply
version: "2021.05-1"
